Add validation to custom_metrics
nodecross/nodex pull request #355
Opened 2024-07-24 23:08 UTC by c0ridrew

2024-07-24 23:57 UTC, tzskp1 requested changes
LGTM except for minor syntax issues.

2024-07-24 23:57 UTC, tzskp1 commented on src/repository/custom_metric_repository.rs
> +    async fn save(&self, request: CustomMetricStoreRequest) -> anyhow::Result<(), anyhow::Error>;
This change is not required.
Because `anyhow::Result<T, anyhow::Error>` = `anyhow::Result<T>`

2024-07-24 23:57 UTC, tzskp1 commented on src/usecase/custom_metric_usecase.rs
> +    pub async fn save(&self, request: CustomMetricStoreRequest) -> Result<(), anyhow::Error> {
You should use `anyhow::Result<()>` instead of `Result<(), anyhow::Error>`

2024-07-25 13:34 UTC, ibuibu commented on src/repository/custom_metric_repository.rs
> +    async fn save(&self, request: CustomMetricStoreRequest) -> anyhow::Result<(), anyhow::Error>;
うっ、、、すみません、eventのほうもついでに修正いただけると助かります・・・🙏

2024-07-26 06:39 UTC, tzskp1 approved these changes
ありがとうございます
問題ないと思います(日本語でよかった...)

2024-07-26 06:46 UTC, merged